### ISSUE TITLE
is it possible to dump strings with this ap?

### ISSUE THREAD

**Issue by israpps** [eurotools/eurochef#26]
I've been looking for info from time to time to translate predator concrete jungle

But no clue after the quickbms unpacking and looking at textures with this program

**Comment by israpps** [comment]
> The QuickBMS filelist extractor is obsolete, as it misses a good chunk of each EDB file, especially for files with many sections, like text, you won't find any UTF-16 strings in those trimmed files. So extract your `Text.edb` correctly.

Eurochef can't unpack the predator filelist.000

It complains of unsupported version or something like that
So I guess quickbms is still useful...

**Comment by cohaereo** [comment]
> It complains of unsupported version or something like that So I guess quickbms is still useful...

You need to open the .bin file, not the .000 file

**Comment by Swyter** [comment]
> > The QuickBMS filelist extractor is obsolete, as it misses a good chunk of each EDB file, especially for files with many sections, like text, you won't find any UTF-16 strings in those trimmed files. So extract your `Text.edb` correctly.
> 
> Eurochef can't unpack the predator filelist.000
> 
> It complains of unsupported version or something like that So I guess quickbms is still useful...

As I said, it's as useful as a bottomless glass, it's extracting a textless `Text.edb`.

**Comment by israpps** [comment]
will you ever support dumping the data I'm looking for and repacking?

I guess that if you dont the other option would be trying to get more info from the game ELF with ghidra...

I wanted to translate this game so badly...

**Comment by cohaereo** [comment]
> will you ever support dumping the data I'm looking for and repacking? (or you only care for sphinx and others?)
> 
> I guess that if you dont the other option would be trying to get more info from the game ELF with ghidra...
> 
> I wanted to translate this game so badly...

Reading spreadsheets (which are used for text) is supported by eurochef. Writing/repacking is not supported yet.

**Comment by israpps** [comment]
> > will you ever support dumping the data I'm looking for and repacking? (or you only care for sphinx and others?)
> > I guess that if you dont the other option would be trying to get more info from the game ELF with ghidra...
> > I wanted to translate this game so badly...
> 
> Reading spreadsheets (which are used for text) is supported by eurochef. Writing/repacking is not supported yet.

 it seems not this one... or i'm missing something else?
![image](https://github.com/eurotools/eurochef/assets/57065102/8fabb8af-8a89-485f-81fa-1ed6785c3156)

**Comment by cohaereo** [comment]
Data spreadsheets are not supported yet, but you're not looking for them. Text spreadsheets should work fine

**Comment by israpps** [comment]
> Data spreadsheets are not supported yet, but you're not looking for them. Text spreadsheets should work fine

ok... so the text could be somewhere else....

**Comment by cohaereo** [comment]
My bad, I just realised there's no longer a console output for text spreadsheets, eurochef should have created some CSV files in the `spreadsheets` directory

**Comment by israpps** [comment]
> My bad, I just realised there's no longer a console output for text spreadsheets, eurochef should have created some CSV files in the `spreadsheets` directory

or eurochef is missing something or eurocom decided to hide text spreadsheets in a different way for predator. because I just made a CMD for loop
```cmd
for %a in (predator\binary\_bin_ps2\*.edb) do eurochef-cli.exe edb spreadsheets "%a">>LOL.TXR
```

 and all the edb files trow the error of data spreadsheets or say `No spreadsheets found in file`
 
 and before you ask. yes, I redumped with eurochef, and still same issue

**Comment by israpps** [comment]
theres also no other file on the ISO image

Just PSS VIdeos, IRX modules and IOPRP images, and a 2gb dummy file....

**Comment by israpps** [comment]
tested again...

Got some messages on `stderr`

```console
thread 'main' panicked at 'Failed to read header:
 ╺━━━━━━━━━━━━━━━━━━━━┅ Backtrace ┅━━━━━━━━━━━━━━━━━━━━╸

 0: Error: failed to fill whole buffer
           While parsing field 'hashcode' in EXGeoCommonArrayElement
     at eurochef-edb\src\array.rs:250
 1: While parsing field 'common' in EXGeoSpreadSheetHeader
     at eurochef-edb\src\common.rs:147
 2: While parsing field 'spreadsheet_list' in EXGeoHeader
     at eurochef-edb\src\header.rs:53

 ╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸

', eurochef\cli\src\edb\spreadsheets.rs:24:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Failed to read header:
 ╺━━━━━━━━━━━━━━━━━━━━┅ Backtrace ┅━━━━━━━━━━━━━━━━━━━━╸

 0: Error: Se ha intentado mover el puntero del archivo más allá del inicio del archivo. (os error 131)
           While parsing field 'font_list' in EXGeoHeader
     at eurochef-edb\src\header.rs:54

 ╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸

', eurochef\cli\src\edb\spreadsheets.rs:24:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by israpps** [comment]
seems theres more interesting things here...

Predator has two custom IRX modules

`EXAudCD.irx` & `EXAudDVD.irx`

Maybe these two are in charge of creating that `x:/` drive I see on ghidra

**Comment by Swyter** [comment]
Those are the audio streaming parts of EngineX that run on the PS2 IOP for async playback and bypass the Emotion Engine.

The virtual `X:` drive from where the filelist is created is documented in the Sphinx modding tools, it's the same for every other project. The game at runtime doesn't care about these paths, it just uses hashcodes to retrieve them. Maybe not for SFX files.

**Comment by israpps** [comment]
> Those are the audio streaming parts of EngineX that run on the PS2 IOP for async playback and bypass the Emotion Engine.
> 
> The virtual `X:` drive from where the filelist is created is documented in the Sphinx modding tools, it's the same for every other project. The game at runtime doesn't care about these paths, it just uses hashcodes to retrieve them. Maybe not for SFX files.

yeah, found out that As soon as I opened the IRX with ghidra and saw the printf() on `_start()`
